// src/pages/Home/components/About.tsx
import {motion} from 'framer-motion';
import {TypeAnimation} from "react-type-animation";
import {HoverScale, WavingHand} from "../../../components";
import {useSocialStore} from "../../../stores/social.store.ts";
import {cn} from "../../../lib/utils.ts";
import {Fragment} from "react";
import {FaRegHandPointDown} from "react-icons/fa";
import {useLenis} from "lenis/react";

const SocialLinks = () => {
  const {aboutItems} = useSocialStore();
  return (
    <Fragment>
      <div className="flex space-x-3">
        {aboutItems.map((item, index) => (
          <HoverScale key={index}>
            <a
              href={item.link}
              className="text-neutral-400 tooltip tooltip-bottom"
              aria-label={item.id}
              data-tip={item.label}
              rel="noopener noreferrer"
              target="_blank"
            >
              <item.icon className={cn(
                "text-3xl",
                'hover:text-white',
              )}/>
            </a>
          </HoverScale>
        ))}
      </div>

    </Fragment>
  )
}

const ScrollDown = () => {
  const lenis = useLenis();
  return (
    <button
      className="flex flex-col items-center group motion-safe:animate-bounce text-neutral-400 space-y-2"
      onClick={() => lenis?.scrollTo('#expertise')}
    >
      <p className="group-hover:text-white">
        Scroll down to see more
      </p>
      <div className="group-hover:text-white">
        <div className="flex justify-center">
          <FaRegHandPointDown className="text-2xl"/>
        </div>
      </div>
    </button>
  )
}

export default function About() {
  return (
    <motion.section
      id="about"
      className='text-white h-screen w-full bg-slate-950 grid sticky top-0 items-center justify-center'
      initial={{opacity: 0, y: 50}}
      animate={{opacity: 1, y: 0}}
      transition={{duration: 0.5, ease: 'easeOut'}}
    >

      <div className="container max-w-screen-2xl mx-auto items-center tracking-tight leading-[120%]">
        <p className="text-6xl">
          Hi, I'm <span className="text-7xl font-bold"> Ly Phuoc Hiep. </span>
          <WavingHand/>
        </p>

        <p className="text-3xl mt-10">
          <TypeAnimation
            sequence={[
              //
              "A passionate Software Engineer with over 4 years of experience.",
              300,
              // Java
              "Specialize in Java with Spring Framework.",
              300,
              "Specialize in Java with Vert.x.",
              300,
              "Specialize in Java with JPA.",
              300,
              // JavaScript/TypeScript
              "Also specialize in JavaScript/TypeScript with React.",
              300,
              "Also specialize in JavaScript/TypeScript with JQuery.",
              300,
              "Also specialize in JavaScript/TypeScript with VueJS.",
              300,
              "Also specialize in JavaScript/TypeScript with TailwindCSS.",
              300,
              //
              "Love to create robust, scalable, and maintainable software.",
              300,
              "And love to learn new technologies and frameworks.",
              300,
            ]}
            wrapper="span"
            speed={60}
            repeat={Infinity}
          />
        </p>

        <div className="mt-10">
          <SocialLinks/>
        </div>
      </div>

      <div className="absolute bottom-10 w-full justify-center items-center flex">
        <ScrollDown/>
      </div>

    </motion.section>
  )
}

// src/views/About.vue
<template>

  <div class="h-screen w-screen
              flex items-center justify-center
              background bg-cover bg-center
             ">
    <div class="px-2 md:px-24 lg:px-36 xl:px-64 2xl:px-96 space-y-2">


      <p class="text-5xl md:text-8xl font-bold text-white">
        Hiep Phuoc Ly
      </p>

      <div class="ml-2 space-y-2">
        <p class="text-2xl font-bold text-white">
          Software Engineer
        </p>

        <div class="w-full md:w-5/6 2xl:w-4/6 space-y-2">
          <p class="">
            I am a seasoned Software Engineer with over 2.5 years of practical experience, dedicated to constructing
            robust backend solutions.
          </p>
          <p>
            Primarily, I specialize in Java programming, often working with frameworks such as Vert.x and the Spring
            Framework.
          </p>
          <p>
            Additionally, I possess proficiency in TypeScript, and I've applied this expertise to frontend
            technologies like Vue.js and React.
          </p>
        </div>
        <p class="w-full md:w-2/3 2xl:w-3/6 text-g">

        </p>
      </div>

      <div class="flex pt-5 ml-2 space-x-3">
        <a v-for="(contact, index) in contacts"
           :key="index"
           :data-tip="contact.url"
           :href="contact.url"
           class="tooltip" rel="noopener noreferrer"
           target="_blank">
          <font-awesome-icon :icon="contact.icon" class="h-7 w-7 text-gray-500 hover:text-white"/>
        </a>

      </div>
    </div>

    <!--Scroll To Expertise-->
    <div class="absolute bottom-10">
      <button class="flex
                     justify-center
                     group
                     motion-safe:animate-bounce"
              @click="menuStore.goToMenuByHash(MENU_MAP.expertise)">
        <div class="group-hover:text-white">
          <p>
            {{ MENU_MAP.expertise }}
          </p>
          <div class="flex justify-center">
            <font-awesome-icon :icon="['fas', 'angles-down']"/>
          </div>
        </div>
      </button>
    </div>
    <!--End Scroll To Expertise-->

  </div>
</template>

<script lang="ts" setup>
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {useMenuStore} from "../store/menu.store.ts";
import {CONTACT_MAP, MENU_MAP} from "../common/constants.ts";

const menuStore = useMenuStore();

const contacts = [
  CONTACT_MAP.github,
  CONTACT_MAP.gmail,
  CONTACT_MAP.facebook
];
</script>

<style scoped>

</style>
